### ISSUE TITLE
Manage endpoints not working

### ISSUE THREAD

**Issue by maloykr** [cerner/ignite-endpoints#1]
I've tested out a few manage endpoints after going to /metadata and I get 500 errors pretty consistently.  Do manage url's work with these patient endpoints?  

Thanks,
kevin.

**Comment by MaxPhilips** [comment]
I just spot checked some manage endpoints and did not run into any that were returning 500. Can you post some specific ones that are not working so we can investigate?

Thanks,
Max (Cerner)

**Comment by maloykr** [comment]
I tried in chrome/safari/firefox 

https://authorization.cerner.com/tenants/8004d35e-3cbe-40a8-8f64-f3def78d8499/personas/patient/my-authorizations

and I get 500 for ABC Pediatrics

I would expect a login screen to appear, correct?

k.

**Comment by MaxPhilips** [comment]
I tested by hitting the URLs outside of a browser, e.g. using Postman or cURL, and I got a 200 with a login screen as you are expecting

```
curl -X GET https://authorization.cerner.com/tenants/8004d35e-3cbe-40a8-8f64-f3def78d8499/personas/patient/my-authorizations
```

Looks like testing in a browser I do get a 303 then a 500. I will double check that this is expected.

**Comment by robmaag** [comment]
Hi, Pertaining to Cerner's FHIR Endpoints (list supplied by Cerner) are these endpoints verified and valid? What is the verification process that Cerner uses to verify these endpoints?

**Comment by robmaag** [comment]
Hi, I am interested in obtaining an understanding of the Cerner FHIR Endpoints that are listed in GitHub. What is the policy behind the FHIR Endpoints in terms of a. reliability and b. how often are they verified to be working?
